#! /bin/bash
#
# builds .deb debian packages
#
# places .debs in /packages
#

# exit on error
set -e

WD=$(dirname $0)

###

cd $WD

# build visual
cd rc-visual
./configure --prefix=/usr/local
make
sudo sh make_deb.sh
cp *.deb ../packages

cd ../

# build unitd
cd rc-unitd
./configure --prefix=/usr/local
make
sudo sh make_deb.sh
cp *.deb ../packages

cd ../

# build robotcowboy
cd packages/make_deb
sudo sh make_deb

