#! /bin/bash

# exit on error
set -e

WD=$(dirname $0)

###

cd $WD

# clean packages
rm -rf packages/*.deb

# clean visual
cd rc-visual
make clean
rm -rf *.deb *.tgz

cd ../

# clean unitd
cd rc-unitd
make clean
rm -rf *.deb *.tgz

cd ../

