#! /bin/bash

# exit on error
set -e

WD=$(dirname $0)

# fetch version using tag name
VISUAL_VER_TAG=rc-visual-0.4.0-xmlfile
UNITD_VER_TAG=rc-unitd-0.3.0

###

cd $WD

# get sources
git clone git://github.com/danomatika/rc-visual.git
git clone git://github.com/danomatika/rc-unitd.git

# set tags
cd rc-visual
git checkout $VISUAL_VER_TAG
cd ../
cd rc-unitd
git checkout $UNITD_VER_TAG

