#!/bin/bash
#
#	runs at MEMORY mount
#	called by starts_pd and memory_add	

#
# tell pd to load the playlist
rc_pd_control load playlist "/media/MEMORY/simpleScience/playlist.txt"
sleep 1

# which playlist?
rc_pd_control play "/media/MEMORY/simpleScience.wav"

