#! /bin/bash
#
# scripts install script
#
INSTALL_CMD="cp -xR"

# clean up gedit temp files
rm ./*~

# install rc bin scripts
$INSTALL_CMD rc_* /usr/local/bin/

# setup udev scripts
mkdir -p /etc/udev
mkdir -p /etc/udev/rules.d
$INSTALL_CMD 51-rc-visual.rules /etc/udev/rules.d/
$INSTALL_CMD 85-memory.rules /etc/udev/rules.d/

# rc-unitd joy_names file
mkdir -p /etc/rc-unitd
#rm /etc/rc-unitd/joy_names.conf # delete if existing
$INSTALL_CMD joy_names.conf /etc/rc-unitd/

# pdsettings file and asoundrc
mkdir -p /usr/local/lib/robotcowboy
$INSTALL_CMD pdsettings /usr/local/lib/robotcowboy/
$INSTALL_CMD asoundrc /usr/local/lib/robotcowboy/

# puredata init script
#mkdir -p /etc/init.d
#$INSTALL_CMD puredata /etc/init.d

