#! /bin/bash

# inhibit the screensaver 
#(gnome-screensaver-command --inhibit -n "rc-visual" -r "no screensaver during show!" &)

# grab mode
MODE="window"
if [ "$1" != "" ] ; then
	MODE=$1
fi

# go visual
rc-visual -f /Users/dano/Projects/robotcowboy/pd/visual/visual_sprites.xml -n 1 -m $MODE -a 17.0.0.101 -r 17.0.0.100

# reenable screensaver
#killall gnome-screensaver-command
