#!/bin/bash
#
#	stops puredata
#	called by /etc/init.d/puredata	
#

# kill the starts_pd sript if it is still running and leave
#PID=$(pidof /bin/bash ./starts_pd)
#if [ "$PID" != "" ] ; then
#	echo "stops_pd: starts_pd is still running, terminating"	
#	kill $PID
#	exit 0
#fi

# stop pd
if [ "$(pidof pd)" != "" ] ; then

	echo "rc_stops_pd: stopping pd"

	# stop a playing song just in case
	rc_pd_control transport stop
	sleep 1

	# play the good bye sample
	echo "unit /pd/unitd/shutdown stop" | pdsend 3333 localhost udp
	sleep 3

	# stop pd
	killall pd

	sleep 0.5
fi


# stop jackd
if [ "$(pidof jackd)" != "" ] ; then

	echo "rc_stops_pd: stopping jackd"

	killall jackd

	sleep 0.5
fi

# stop rc-unitd
if [ "$(pidof rc-unitd)" != "" ] ; then

	echo "rc_stops_pd: stopping rc-unitd"

	killall rc-unitd

	sleep 0.25
fi

